/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F465_12305();
extern void F467_12467();
extern void F465_12309();
extern void F468_12471();
extern void F470_12635();
extern void F468_12476();
extern void F614_10099();
extern void F589_12151();
extern void F187_5337();
extern EIF_REFERENCE F187_5324();
extern EIF_BOOLEAN F187_5336();
extern EIF_BOOLEAN F187_5344();
extern void F187_5346();
extern void F187_5347();
extern void F187_5348();
extern void F170_5131();
extern EIF_TYPED_VALUE F170_5132();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F465_12305;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F465_12309;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F468_12471;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F468_12476;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F614_10099;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F467_12467;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F470_12635;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F589_12151;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F187_5337;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F187_5336;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F187_5324;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F187_5344;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F187_5346;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F187_5347;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F187_5348;

	egc_str_dtype = 466;

	egc_immstr8_dtype = 465;

	egc_str32_dtype = 469;

	egc_immstr32_dtype = 468;
	egc_arr_dtype = 613;
	egc_tup_dtype = 418;
	egc_disp_rout_id = 7012;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0479;
	egc_sp_wchar = 0x0317;
	egc_sp_bool = 0x048C;
	egc_sp_uint8 = 0x0451;
	egc_sp_uint16 = 0x042D;
	egc_sp_uint32 = 0x02BB;
	egc_sp_uint64 = 0x0336;
	egc_sp_int8 = 0x03E5;
	egc_sp_int16 = 0x03C1;
	egc_sp_int32 = 0x0287;
	egc_sp_int64 = 0x0409;
	egc_sp_real32 = 0x0379;
	egc_sp_real64 = 0x039D;
	egc_sp_pointer = 0x02DC;
	egc_sp_ref = 0x026B;

	egc_uint8_dtype = 441;
	egc_uint16_dtype = 438;
	egc_uint32_dtype = 435;
	egc_uint64_dtype = 432;
	egc_int8_dtype = 429;
	egc_int16_dtype = 426;
	egc_int32_dtype = 423;
	egc_int64_dtype = 420;
	egc_bool_dtype = 456;
	egc_real32_dtype = 444;
	egc_char_dtype = 453;
	egc_wchar_dtype = 450;
	egc_real64_dtype = 447;
	egc_point_dtype = 459;

	egc_exception_dtype = 216;
	egc_except_emnger_dtype = 186;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_web";
	egc_system_location = "D:\\prod\\simple_web\\EIFGENs\\simple_web_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1763765086;
	egc_has_old_special_semantic = 0;
	scount = 1261;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 3232;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 6975;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 12489;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 169;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F170_5131;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F170_5132;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 59; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 308; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 543; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
