/*
 * Code for class WEL_WINDOW_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F6_407(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_408(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_409(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_410(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_411(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_412(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_413(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_414(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_415(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_416(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_417(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_418(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_419(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_420(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_421(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_422(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_423(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_424(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_425(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_426(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_427(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_428(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_429(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_430(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_431(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_432(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_433(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_434(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_435(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_436(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_437(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_438(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_439(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_440(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_441(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_442(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_443(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_444(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_445(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_446(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_447(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_448(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_449(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_450(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_451(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_452(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_453(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_454(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_455(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_456(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_457(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_458(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_459(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_460(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_461(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_462(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_463(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_464(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_465(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_466(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_467(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_468(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_469(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_470(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_471(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_472(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_473(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_474(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_475(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_476(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_477(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_478(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_479(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_480(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_481(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_482(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_483(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_484(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_485(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_486(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_487(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_488(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_489(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_490(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_491(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_492(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_493(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_494(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_495(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_496(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_497(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_498(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_499(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_500(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_501(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_502(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_503(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_504(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_505(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_506(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_507(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_508(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_509(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_510(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_511(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_512(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_513(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_514(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_515(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_516(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_517(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_518(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_519(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_520(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_521(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_522(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_523(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_524(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_525(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_526(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_527(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_528(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_529(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_530(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_531(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_532(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_533(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_534(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_535(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_536(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_537(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_538(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_539(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_540(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_541(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_542(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_543(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_544(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_545(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_546(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_547(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_548(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_549(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_550(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_551(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_552(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_553(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_554(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_555(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_556(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_557(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_558(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_559(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_560(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_561(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_562(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_563(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_564(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_565(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_566(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_567(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_568(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_569(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_570(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_571(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_572(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_573(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_574(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_575(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_576(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_577(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_578(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_579(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_580(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_581(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_582(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_583(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_584(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_585(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_586(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_587(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_588(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_589(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_590(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_591(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_592(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_593(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_594(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_595(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_596(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_597(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_598(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_599(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_600(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_601(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_602(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_603(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_604(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_605(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_606(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_607(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_608(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_609(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_610(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_611(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_612(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_613(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_614(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_615(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_616(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_617(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_618(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_619(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_620(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_621(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_622(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_623(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_624(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_625(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_626(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_627(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_628(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_629(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_630(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_631(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_632(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_633(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_634(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_635(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_636(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_637(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_638(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_639(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_640(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_641(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_642(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_643(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_644(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_645(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_646(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_647(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_648(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_649(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_650(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_651(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_652(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_653(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_654(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_655(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_656(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_657(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_658(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_659(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_660(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_661(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_662(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_663(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_664(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_665(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_666(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_667(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_668(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_669(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_670(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_671(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_672(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_673(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_674(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_675(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_676(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_677(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_678(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_679(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_680(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_681(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_682(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_683(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_684(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_685(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_686(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_687(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_688(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_689(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_690(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_691(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_692(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_693(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_694(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_695(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_696(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_697(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_698(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_699(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_700(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_701(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_702(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_703(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_704(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_705(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_706(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_707(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_708(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_709(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_710(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_711(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_712(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_713(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_714(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_715(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_716(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_717(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_718(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_719(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_720(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_721(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_722(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_723(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_724(EIF_REFERENCE);
extern EIF_TYPED_VALUE F6_725(EIF_REFERENCE);
extern void EIF_Minit6(void);

#ifdef __cplusplus
}
#endif

#include <winuser.h>

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_WINDOW_CONSTANTS}.wm_null */
EIF_TYPED_VALUE F6_407 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_create */
EIF_TYPED_VALUE F6_408 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_destroy */
EIF_TYPED_VALUE F6_409 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_move */
EIF_TYPED_VALUE F6_410 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_size */
EIF_TYPED_VALUE F6_411 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_activate */
EIF_TYPED_VALUE F6_412 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_setfocus */
EIF_TYPED_VALUE F6_413 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_killfocus */
EIF_TYPED_VALUE F6_414 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_enable */
EIF_TYPED_VALUE F6_415 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_setredraw */
EIF_TYPED_VALUE F6_416 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_settext */
EIF_TYPED_VALUE F6_417 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_gettext */
EIF_TYPED_VALUE F6_418 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_gettextlength */
EIF_TYPED_VALUE F6_419 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_paint */
EIF_TYPED_VALUE F6_420 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_close */
EIF_TYPED_VALUE F6_421 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_queryendsession */
EIF_TYPED_VALUE F6_422 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 17L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_quit */
EIF_TYPED_VALUE F6_423 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_queryopen */
EIF_TYPED_VALUE F6_424 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 19L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_erasebkgnd */
EIF_TYPED_VALUE F6_425 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_syscolorchange */
EIF_TYPED_VALUE F6_426 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 21L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_endsession */
EIF_TYPED_VALUE F6_427 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 22L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_showwindow */
EIF_TYPED_VALUE F6_428 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 24L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_wininichange */
EIF_TYPED_VALUE F6_429 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 26L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_settingchange */
EIF_TYPED_VALUE F6_430 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 26L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_devmodechange */
EIF_TYPED_VALUE F6_431 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 27L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_activateapp */
EIF_TYPED_VALUE F6_432 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 28L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_fontchange */
EIF_TYPED_VALUE F6_433 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 29L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_timechange */
EIF_TYPED_VALUE F6_434 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 30L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_cancelmode */
EIF_TYPED_VALUE F6_435 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 31L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_setcursor */
EIF_TYPED_VALUE F6_436 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mouseactivate */
EIF_TYPED_VALUE F6_437 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 33L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_childactivate */
EIF_TYPED_VALUE F6_438 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 34L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_queuesync */
EIF_TYPED_VALUE F6_439 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 35L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_getminmaxinfo */
EIF_TYPED_VALUE F6_440 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 36L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_painticon */
EIF_TYPED_VALUE F6_441 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 38L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_iconerasebkgnd */
EIF_TYPED_VALUE F6_442 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 39L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_nextdlgctl */
EIF_TYPED_VALUE F6_443 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 40L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_spoolerstatus */
EIF_TYPED_VALUE F6_444 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 42L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_drawitem */
EIF_TYPED_VALUE F6_445 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 43L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_measureitem */
EIF_TYPED_VALUE F6_446 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 44L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_deleteitem */
EIF_TYPED_VALUE F6_447 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 45L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_vkeytoitem */
EIF_TYPED_VALUE F6_448 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 46L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_chartoitem */
EIF_TYPED_VALUE F6_449 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 47L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_setfont */
EIF_TYPED_VALUE F6_450 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 48L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_getfont */
EIF_TYPED_VALUE F6_451 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 49L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_sethotkey */
EIF_TYPED_VALUE F6_452 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 50L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_gethotkey */
EIF_TYPED_VALUE F6_453 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 51L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_querydragicon */
EIF_TYPED_VALUE F6_454 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 55L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_compareitem */
EIF_TYPED_VALUE F6_455 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 57L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_getobject */
EIF_TYPED_VALUE F6_456 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 61L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_compacting */
EIF_TYPED_VALUE F6_457 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 65L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_commnotify */
EIF_TYPED_VALUE F6_458 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 68L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_windowposchanging */
EIF_TYPED_VALUE F6_459 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 70L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_windowposchanged */
EIF_TYPED_VALUE F6_460 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 71L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_power */
EIF_TYPED_VALUE F6_461 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 72L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_copydata */
EIF_TYPED_VALUE F6_462 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 74L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_canceljournal */
EIF_TYPED_VALUE F6_463 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 75L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_notify */
EIF_TYPED_VALUE F6_464 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 78L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_inputlangchangerequest */
EIF_TYPED_VALUE F6_465 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 80L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_inputlangchange */
EIF_TYPED_VALUE F6_466 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 81L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_tcard */
EIF_TYPED_VALUE F6_467 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 82L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_help */
EIF_TYPED_VALUE F6_468 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 83L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_userchanged */
EIF_TYPED_VALUE F6_469 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 84L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_notifyformat */
EIF_TYPED_VALUE F6_470 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 85L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_contextmenu */
EIF_TYPED_VALUE F6_471 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 123L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_stylechanging */
EIF_TYPED_VALUE F6_472 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 124L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_stylechanged */
EIF_TYPED_VALUE F6_473 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 125L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_displaychange */
EIF_TYPED_VALUE F6_474 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 126L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_geticon */
EIF_TYPED_VALUE F6_475 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 127L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_seticon */
EIF_TYPED_VALUE F6_476 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 128L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_nccreate */
EIF_TYPED_VALUE F6_477 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 129L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncdestroy */
EIF_TYPED_VALUE F6_478 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 130L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_nccalcsize */
EIF_TYPED_VALUE F6_479 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 131L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_nchittest */
EIF_TYPED_VALUE F6_480 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 132L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncpaint */
EIF_TYPED_VALUE F6_481 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 133L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncactivate */
EIF_TYPED_VALUE F6_482 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 134L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_getdlgcode */
EIF_TYPED_VALUE F6_483 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 135L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_syncpaint */
EIF_TYPED_VALUE F6_484 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 136L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncmousemove */
EIF_TYPED_VALUE F6_485 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 160L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_nclbuttondown */
EIF_TYPED_VALUE F6_486 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 161L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_nclbuttonup */
EIF_TYPED_VALUE F6_487 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 162L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_nclbuttondblclk */
EIF_TYPED_VALUE F6_488 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 163L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncrbuttondown */
EIF_TYPED_VALUE F6_489 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 164L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncrbuttonup */
EIF_TYPED_VALUE F6_490 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 165L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncrbuttondblclk */
EIF_TYPED_VALUE F6_491 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 166L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncmbuttondown */
EIF_TYPED_VALUE F6_492 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 167L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncmbuttonup */
EIF_TYPED_VALUE F6_493 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 168L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncmbuttondblclk */
EIF_TYPED_VALUE F6_494 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 169L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncxbuttondown */
EIF_TYPED_VALUE F6_495 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 171L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncxbuttonup */
EIF_TYPED_VALUE F6_496 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 172L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncxbuttondblclk */
EIF_TYPED_VALUE F6_497 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 173L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_keydown */
EIF_TYPED_VALUE F6_498 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 256L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_keyfirst */
EIF_TYPED_VALUE F6_499 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 256L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_keyup */
EIF_TYPED_VALUE F6_500 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 257L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_char */
EIF_TYPED_VALUE F6_501 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 258L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_deadchar */
EIF_TYPED_VALUE F6_502 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 259L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_syskeydown */
EIF_TYPED_VALUE F6_503 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 260L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_syskeyup */
EIF_TYPED_VALUE F6_504 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 261L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_syschar */
EIF_TYPED_VALUE F6_505 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 262L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_sysdeadchar */
EIF_TYPED_VALUE F6_506 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 263L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_keylast */
EIF_TYPED_VALUE F6_507 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "wm_keylast";
	RTEX;
	EIF_INTEGER_32 Result = ((EIF_INTEGER_32) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 504);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 1);
	RTDBGEAA(5, Current, 504);
	RTIV(Current, RTAL);
	Result = (EIF_INTEGER_32) WM_KEYLAST;
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(1);
	RTDBGLE;
	RTMD(1);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_startcomposition */
EIF_TYPED_VALUE F6_508 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 269L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_endcomposition */
EIF_TYPED_VALUE F6_509 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 270L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_composition */
EIF_TYPED_VALUE F6_510 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 271L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_keylast */
EIF_TYPED_VALUE F6_511 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "wm_ime_keylast";
	RTEX;
	EIF_INTEGER_32 Result = ((EIF_INTEGER_32) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 508);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 1);
	RTDBGEAA(5, Current, 508);
	RTIV(Current, RTAL);
	Result = (EIF_INTEGER_32) WM_IME_KEYLAST;
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(1);
	RTDBGLE;
	RTMD(1);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
}

/* {WEL_WINDOW_CONSTANTS}.wm_initdialog */
EIF_TYPED_VALUE F6_512 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 272L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_command */
EIF_TYPED_VALUE F6_513 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 273L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_syscommand */
EIF_TYPED_VALUE F6_514 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 274L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_timer */
EIF_TYPED_VALUE F6_515 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 275L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_hscroll */
EIF_TYPED_VALUE F6_516 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 276L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_vscroll */
EIF_TYPED_VALUE F6_517 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 277L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_initmenu */
EIF_TYPED_VALUE F6_518 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 278L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_initmenupopup */
EIF_TYPED_VALUE F6_519 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 279L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_menuselect */
EIF_TYPED_VALUE F6_520 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 287L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_menuchar */
EIF_TYPED_VALUE F6_521 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 288L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_enteridle */
EIF_TYPED_VALUE F6_522 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 289L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_menurbuttonup */
EIF_TYPED_VALUE F6_523 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 290L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_menudrag */
EIF_TYPED_VALUE F6_524 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 291L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_menugetobject */
EIF_TYPED_VALUE F6_525 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 292L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_uninitmenupopup */
EIF_TYPED_VALUE F6_526 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 293L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_menucommand */
EIF_TYPED_VALUE F6_527 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 294L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_changeuistate */
EIF_TYPED_VALUE F6_528 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 295L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_updateuistate */
EIF_TYPED_VALUE F6_529 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 296L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_queryuistate */
EIF_TYPED_VALUE F6_530 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 297L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ctlcolor */
EIF_TYPED_VALUE F6_531 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 25L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ctlcolormsgbox */
EIF_TYPED_VALUE F6_532 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 306L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ctlcoloredit */
EIF_TYPED_VALUE F6_533 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 307L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ctlcolorlistbox */
EIF_TYPED_VALUE F6_534 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 308L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ctlcolorbtn */
EIF_TYPED_VALUE F6_535 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 309L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ctlcolordlg */
EIF_TYPED_VALUE F6_536 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 310L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ctlcolorscrollbar */
EIF_TYPED_VALUE F6_537 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 311L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ctlcolorstatic */
EIF_TYPED_VALUE F6_538 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 312L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mousemove */
EIF_TYPED_VALUE F6_539 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mousefirst */
EIF_TYPED_VALUE F6_540 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_lbuttondown */
EIF_TYPED_VALUE F6_541 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 513L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_lbuttonup */
EIF_TYPED_VALUE F6_542 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 514L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_lbuttondblclk */
EIF_TYPED_VALUE F6_543 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 515L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_rbuttondown */
EIF_TYPED_VALUE F6_544 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 516L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_rbuttonup */
EIF_TYPED_VALUE F6_545 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 517L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_rbuttondblclk */
EIF_TYPED_VALUE F6_546 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 518L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mbuttondown */
EIF_TYPED_VALUE F6_547 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 519L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mbuttonup */
EIF_TYPED_VALUE F6_548 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 520L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mbuttondblclk */
EIF_TYPED_VALUE F6_549 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 521L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mousewheel */
EIF_TYPED_VALUE F6_550 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 522L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_xbuttondown */
EIF_TYPED_VALUE F6_551 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 523L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_xbuttonup */
EIF_TYPED_VALUE F6_552 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 524L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_xbuttondblclk */
EIF_TYPED_VALUE F6_553 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 525L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mouselast */
EIF_TYPED_VALUE F6_554 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "wm_mouselast";
	RTEX;
	EIF_INTEGER_32 Result = ((EIF_INTEGER_32) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 551);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 1);
	RTDBGEAA(5, Current, 551);
	RTIV(Current, RTAL);
	Result = (EIF_INTEGER_32) WM_MOUSELAST;
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(1);
	RTDBGLE;
	RTMD(1);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
}

/* {WEL_WINDOW_CONSTANTS}.wm_parentnotify */
EIF_TYPED_VALUE F6_555 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 528L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_entermenuloop */
EIF_TYPED_VALUE F6_556 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 529L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_exitmenuloop */
EIF_TYPED_VALUE F6_557 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 530L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_nextmenu */
EIF_TYPED_VALUE F6_558 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 531L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_sizing */
EIF_TYPED_VALUE F6_559 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 532L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_capturechanged */
EIF_TYPED_VALUE F6_560 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 533L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_moving */
EIF_TYPED_VALUE F6_561 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 534L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_powerbroadcast */
EIF_TYPED_VALUE F6_562 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 536L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_devicechange */
EIF_TYPED_VALUE F6_563 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 537L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdicreate */
EIF_TYPED_VALUE F6_564 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 544L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdidestroy */
EIF_TYPED_VALUE F6_565 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 545L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdiactivate */
EIF_TYPED_VALUE F6_566 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 546L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdirestore */
EIF_TYPED_VALUE F6_567 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 547L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdinext */
EIF_TYPED_VALUE F6_568 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 548L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdimaximize */
EIF_TYPED_VALUE F6_569 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 549L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mditile */
EIF_TYPED_VALUE F6_570 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 550L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdicascade */
EIF_TYPED_VALUE F6_571 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 551L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdiiconarrange */
EIF_TYPED_VALUE F6_572 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 552L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdigetactive */
EIF_TYPED_VALUE F6_573 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 553L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdisetmenu */
EIF_TYPED_VALUE F6_574 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 560L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_entersizemove */
EIF_TYPED_VALUE F6_575 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 561L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_exitsizemove */
EIF_TYPED_VALUE F6_576 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 562L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_dropfiles */
EIF_TYPED_VALUE F6_577 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 563L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mdirefreshmenu */
EIF_TYPED_VALUE F6_578 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 564L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_setcontext */
EIF_TYPED_VALUE F6_579 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 641L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_notify */
EIF_TYPED_VALUE F6_580 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 642L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_control */
EIF_TYPED_VALUE F6_581 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 643L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_compositionfull */
EIF_TYPED_VALUE F6_582 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 644L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_select */
EIF_TYPED_VALUE F6_583 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 645L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_char */
EIF_TYPED_VALUE F6_584 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 646L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_request */
EIF_TYPED_VALUE F6_585 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 648L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_keydown */
EIF_TYPED_VALUE F6_586 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 656L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ime_keyup */
EIF_TYPED_VALUE F6_587 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 657L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncmousehover */
EIF_TYPED_VALUE F6_588 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 672L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mousehover */
EIF_TYPED_VALUE F6_589 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 673L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_ncmouseleave */
EIF_TYPED_VALUE F6_590 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 674L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_mouseleave */
EIF_TYPED_VALUE F6_591 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 675L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_cut */
EIF_TYPED_VALUE F6_592 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 768L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_copy */
EIF_TYPED_VALUE F6_593 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 769L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_paste */
EIF_TYPED_VALUE F6_594 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 770L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_clear */
EIF_TYPED_VALUE F6_595 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 771L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_undo */
EIF_TYPED_VALUE F6_596 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 772L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_renderformat */
EIF_TYPED_VALUE F6_597 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 773L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_renderallformats */
EIF_TYPED_VALUE F6_598 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 774L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_destroyclipboard */
EIF_TYPED_VALUE F6_599 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 775L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_drawclipboard */
EIF_TYPED_VALUE F6_600 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 776L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_paintclipboard */
EIF_TYPED_VALUE F6_601 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 777L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_sizeclipboard */
EIF_TYPED_VALUE F6_602 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 779L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_vscrollclipboard */
EIF_TYPED_VALUE F6_603 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 778L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_hscrollclipboard */
EIF_TYPED_VALUE F6_604 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 782L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_askcbformatname */
EIF_TYPED_VALUE F6_605 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 780L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_changecbchain */
EIF_TYPED_VALUE F6_606 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 781L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_querynewpalette */
EIF_TYPED_VALUE F6_607 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 783L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_paletteischanging */
EIF_TYPED_VALUE F6_608 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 784L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_palettechanged */
EIF_TYPED_VALUE F6_609 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 785L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_hotkey */
EIF_TYPED_VALUE F6_610 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 786L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_print */
EIF_TYPED_VALUE F6_611 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 791L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_printclient */
EIF_TYPED_VALUE F6_612 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 792L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_appcommand */
EIF_TYPED_VALUE F6_613 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 793L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_handheldfirst */
EIF_TYPED_VALUE F6_614 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 856L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_handheldlast */
EIF_TYPED_VALUE F6_615 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 863L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_afxfirst */
EIF_TYPED_VALUE F6_616 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 864L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_afxlast */
EIF_TYPED_VALUE F6_617 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 895L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_forwardmsg */
EIF_TYPED_VALUE F6_618 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 895L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_penwinfirst */
EIF_TYPED_VALUE F6_619 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 896L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_penwinlast */
EIF_TYPED_VALUE F6_620 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 911L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_user */
EIF_TYPED_VALUE F6_621 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wm_app */
EIF_TYPED_VALUE F6_622 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32768L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ocm__base */
RTOID (F6_623)
EIF_TYPED_VALUE F6_623 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm__base";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_623);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 620);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 620);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(624, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ((EIF_INTEGER_32) 7168L));
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_command */
RTOID (F6_624)
EIF_TYPED_VALUE F6_624 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_command";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_624);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 621);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 621);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(516, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_ctlcolorbtn */
RTOID (F6_625)
EIF_TYPED_VALUE F6_625 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_ctlcolorbtn";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_625);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 622);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 622);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(538, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_ctlcoloredit */
RTOID (F6_626)
EIF_TYPED_VALUE F6_626 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_ctlcoloredit";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_626);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 623);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 623);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(536, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_ctlcolordlg */
RTOID (F6_627)
EIF_TYPED_VALUE F6_627 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_ctlcolordlg";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_627);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 624);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 624);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(539, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_ctlcolorlistbox */
RTOID (F6_628)
EIF_TYPED_VALUE F6_628 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_ctlcolorlistbox";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_628);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 625);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 625);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(537, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_ctlcolormsgbox */
RTOID (F6_629)
EIF_TYPED_VALUE F6_629 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_ctlcolormsgbox";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_629);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 626);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 626);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(535, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_ctlcolorscrollbar */
RTOID (F6_630)
EIF_TYPED_VALUE F6_630 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_ctlcolorscrollbar";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_630);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 627);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 627);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(540, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_ctlcolorstatic */
RTOID (F6_631)
EIF_TYPED_VALUE F6_631 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_ctlcolorstatic";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_631);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 628);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 628);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(541, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_ctlcolor */
RTOID (F6_632)
EIF_TYPED_VALUE F6_632 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_ctlcolor";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_632);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 629);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 629);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(534, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_drawitem */
RTOID (F6_633)
EIF_TYPED_VALUE F6_633 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_drawitem";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_633);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 630);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 630);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(448, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_measureitem */
RTOID (F6_634)
EIF_TYPED_VALUE F6_634 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_measureitem";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_634);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 631);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 631);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(449, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_deleteitem */
RTOID (F6_635)
EIF_TYPED_VALUE F6_635 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_deleteitem";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_635);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 632);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 632);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(450, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_vkeytoitem */
RTOID (F6_636)
EIF_TYPED_VALUE F6_636 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_vkeytoitem";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_636);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 633);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 633);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(451, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_chartoitem */
RTOID (F6_637)
EIF_TYPED_VALUE F6_637 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_chartoitem";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_637);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 634);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 634);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(452, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_compareitem */
RTOID (F6_638)
EIF_TYPED_VALUE F6_638 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_compareitem";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_638);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 635);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 635);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(458, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_hscroll */
RTOID (F6_639)
EIF_TYPED_VALUE F6_639 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_hscroll";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_639);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 636);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 636);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(519, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_vscroll */
RTOID (F6_640)
EIF_TYPED_VALUE F6_640 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_vscroll";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_640);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 637);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 637);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(520, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_parentnotify */
RTOID (F6_641)
EIF_TYPED_VALUE F6_641 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_parentnotify";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_641);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 638);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 638);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(558, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ocm_notify */
RTOID (F6_642)
EIF_TYPED_VALUE F6_642 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "ocm_notify";
	RTEX;
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	RTCDD;
	RTSN;
	RTDA;
	RTLD;
	
#define Result RTOTRB(EIF_INTEGER_32)
	RTOTDB(EIF_INTEGER_32, F6_642);
	dtype = Dtype(Current);

	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 5, Current, 0, 0, 639);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(5, Current, 639);
	RTIV(Current, RTAL);
	RTOTP;
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(626, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(467, dtype))(Current)).it_i4);
	Result = (EIF_INTEGER_32) (EIF_INTEGER_32) (ti4_1 + ti4_2);
	RTVI(Current, RTAL);
	RTRS;
	RTOTE;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
#undef Result
}

/* {WEL_WINDOW_CONSTANTS}.ws_overlapped */
EIF_TYPED_VALUE F6_643 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_tiled */
EIF_TYPED_VALUE F6_644 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_popup */
EIF_TYPED_VALUE F6_645 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0x80000000L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_child */
EIF_TYPED_VALUE F6_646 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1073741824L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_clipsiblings */
EIF_TYPED_VALUE F6_647 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 67108864L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_clipchildren */
EIF_TYPED_VALUE F6_648 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 33554432L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_visible */
EIF_TYPED_VALUE F6_649 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 268435456L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_disabled */
EIF_TYPED_VALUE F6_650 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 134217728L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_minimize */
EIF_TYPED_VALUE F6_651 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 536870912L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_iconic */
EIF_TYPED_VALUE F6_652 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 536870912L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_maximize */
EIF_TYPED_VALUE F6_653 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16777216L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_caption */
EIF_TYPED_VALUE F6_654 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12582912L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_border */
EIF_TYPED_VALUE F6_655 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8388608L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_dlgframe */
EIF_TYPED_VALUE F6_656 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4194304L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_vscroll */
EIF_TYPED_VALUE F6_657 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2097152L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_hscroll */
EIF_TYPED_VALUE F6_658 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1048576L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_sysmenu */
EIF_TYPED_VALUE F6_659 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 524288L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_thickframe */
EIF_TYPED_VALUE F6_660 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 262144L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_sizebox */
EIF_TYPED_VALUE F6_661 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 262144L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_minimizebox */
EIF_TYPED_VALUE F6_662 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 131072L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_maximizebox */
EIF_TYPED_VALUE F6_663 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 65536L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_group */
EIF_TYPED_VALUE F6_664 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 131072L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_tabstop */
EIF_TYPED_VALUE F6_665 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 65536L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_overlappedwindow */
EIF_TYPED_VALUE F6_666 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13565952L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_tiledwindow */
EIF_TYPED_VALUE F6_667 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13565952L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_popupwindow */
EIF_TYPED_VALUE F6_668 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -2138570752L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_childwindow */
EIF_TYPED_VALUE F6_669 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1073741824L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_acceptfiles */
EIF_TYPED_VALUE F6_670 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_clientedge */
EIF_TYPED_VALUE F6_671 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_contexthelp */
EIF_TYPED_VALUE F6_672 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_controlparent */
EIF_TYPED_VALUE F6_673 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 65536L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_dlgmodalframe */
EIF_TYPED_VALUE F6_674 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_left */
EIF_TYPED_VALUE F6_675 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_leftscrollbar */
EIF_TYPED_VALUE F6_676 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16384L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_ltrreading */
EIF_TYPED_VALUE F6_677 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_mdichild */
EIF_TYPED_VALUE F6_678 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 64L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_noparentnotify */
EIF_TYPED_VALUE F6_679 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_overlappedwindow */
EIF_TYPED_VALUE F6_680 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 768L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_palettewindow */
EIF_TYPED_VALUE F6_681 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 392L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_right */
EIF_TYPED_VALUE F6_682 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4096L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_rightscrollbar */
EIF_TYPED_VALUE F6_683 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_rtlreading */
EIF_TYPED_VALUE F6_684 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8192L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_staticedge */
EIF_TYPED_VALUE F6_685 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 131072L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_toolwindow */
EIF_TYPED_VALUE F6_686 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 128L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_topmost */
EIF_TYPED_VALUE F6_687 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_transparent */
EIF_TYPED_VALUE F6_688 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.ws_ex_windowedge */
EIF_TYPED_VALUE F6_689 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 256L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.cw_usedefault */
EIF_TYPED_VALUE F6_690 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0x80000000L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.size_maximized */
EIF_TYPED_VALUE F6_691 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.size_minimized */
EIF_TYPED_VALUE F6_692 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.size_restored */
EIF_TYPED_VALUE F6_693 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.size_maxhide */
EIF_TYPED_VALUE F6_694 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.size_maxshow */
EIF_TYPED_VALUE F6_695 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_hide */
EIF_TYPED_VALUE F6_696 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_minimize */
EIF_TYPED_VALUE F6_697 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_restore */
EIF_TYPED_VALUE F6_698 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_shownormal */
EIF_TYPED_VALUE F6_699 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_show */
EIF_TYPED_VALUE F6_700 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_showmaximized */
EIF_TYPED_VALUE F6_701 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_showminimized */
EIF_TYPED_VALUE F6_702 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_showminnoactive */
EIF_TYPED_VALUE F6_703 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_showna */
EIF_TYPED_VALUE F6_704 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_shownoactivate */
EIF_TYPED_VALUE F6_705 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_parentclosing */
EIF_TYPED_VALUE F6_706 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_parentopening */
EIF_TYPED_VALUE F6_707 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_otherzoom */
EIF_TYPED_VALUE F6_708 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.sw_otherunzoom */
EIF_TYPED_VALUE F6_709 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_nosize */
EIF_TYPED_VALUE F6_710 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_nomove */
EIF_TYPED_VALUE F6_711 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_nozorder */
EIF_TYPED_VALUE F6_712 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_noredraw */
EIF_TYPED_VALUE F6_713 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_noactivate */
EIF_TYPED_VALUE F6_714 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_framechanged */
EIF_TYPED_VALUE F6_715 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_drawframe */
EIF_TYPED_VALUE F6_716 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_showwindow */
EIF_TYPED_VALUE F6_717 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 64L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_hidewindow */
EIF_TYPED_VALUE F6_718 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 128L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_nocopybits */
EIF_TYPED_VALUE F6_719 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 256L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_noownerzorder */
EIF_TYPED_VALUE F6_720 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_noreposition */
EIF_TYPED_VALUE F6_721 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.swp_nosendchanging */
EIF_TYPED_VALUE F6_722 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wa_active */
EIF_TYPED_VALUE F6_723 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wa_clickactive */
EIF_TYPED_VALUE F6_724 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_WINDOW_CONSTANTS}.wa_inactive */
EIF_TYPED_VALUE F6_725 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

void EIF_Minit6 (void)
{
	GTCX
	RTOTS (623,F6_623)
	RTOTS (624,F6_624)
	RTOTS (625,F6_625)
	RTOTS (626,F6_626)
	RTOTS (627,F6_627)
	RTOTS (628,F6_628)
	RTOTS (629,F6_629)
	RTOTS (630,F6_630)
	RTOTS (631,F6_631)
	RTOTS (632,F6_632)
	RTOTS (633,F6_633)
	RTOTS (634,F6_634)
	RTOTS (635,F6_635)
	RTOTS (636,F6_636)
	RTOTS (637,F6_637)
	RTOTS (638,F6_638)
	RTOTS (639,F6_639)
	RTOTS (640,F6_640)
	RTOTS (641,F6_641)
	RTOTS (642,F6_642)
}


#ifdef __cplusplus
}
#endif
