/*
 * Code for class WEL_LANGUAGE_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F100_4033(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4034(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4035(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4036(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4037(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4038(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4039(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4040(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4041(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4042(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4043(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4044(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4045(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4046(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4047(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4048(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4049(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4050(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4051(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4052(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4053(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4054(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4055(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4056(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4057(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4058(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4059(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4060(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4061(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4062(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4063(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4064(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4065(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4066(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4067(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4068(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4069(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4070(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4071(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4072(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4073(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4074(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4075(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4076(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4077(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4078(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4079(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4080(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4081(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4082(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4083(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4084(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4085(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4086(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4087(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4088(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4089(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4090(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4091(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4092(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4093(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4094(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4095(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4096(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4097(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4098(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4099(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4100(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4101(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4102(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4103(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4104(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4105(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4106(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4107(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4108(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4109(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4110(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4111(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4112(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4113(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4114(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4115(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4116(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4117(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4118(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4119(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4120(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4121(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4122(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4123(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4124(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4125(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4126(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4127(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4128(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4129(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4130(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4131(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4132(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4133(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4134(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4135(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4136(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4137(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4138(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4139(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4140(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4141(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4142(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4143(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4144(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4145(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4146(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4147(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4148(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4149(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4150(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4151(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4152(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4153(EIF_REFERENCE);
extern EIF_TYPED_VALUE F100_4154(EIF_REFERENCE);
extern void EIF_Minit100(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_LANGUAGE_CONSTANTS}.lang_neutral */
EIF_TYPED_VALUE F100_4033 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_afrikaans */
EIF_TYPED_VALUE F100_4034 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 54L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_albanian */
EIF_TYPED_VALUE F100_4035 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 28L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_arabic */
EIF_TYPED_VALUE F100_4036 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_basque */
EIF_TYPED_VALUE F100_4037 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 45L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_belarusian */
EIF_TYPED_VALUE F100_4038 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 35L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_bulgarian */
EIF_TYPED_VALUE F100_4039 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_catalan */
EIF_TYPED_VALUE F100_4040 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_chinese */
EIF_TYPED_VALUE F100_4041 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_croatian */
EIF_TYPED_VALUE F100_4042 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 26L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_czech */
EIF_TYPED_VALUE F100_4043 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_danish */
EIF_TYPED_VALUE F100_4044 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_dutch */
EIF_TYPED_VALUE F100_4045 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 19L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_english */
EIF_TYPED_VALUE F100_4046 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_estonian */
EIF_TYPED_VALUE F100_4047 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 37L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_faeroese */
EIF_TYPED_VALUE F100_4048 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 56L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_farsi */
EIF_TYPED_VALUE F100_4049 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 41L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_finnish */
EIF_TYPED_VALUE F100_4050 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_french */
EIF_TYPED_VALUE F100_4051 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_german */
EIF_TYPED_VALUE F100_4052 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_greek */
EIF_TYPED_VALUE F100_4053 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_hebrew */
EIF_TYPED_VALUE F100_4054 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_hungarian */
EIF_TYPED_VALUE F100_4055 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_icelandic */
EIF_TYPED_VALUE F100_4056 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_indonesian */
EIF_TYPED_VALUE F100_4057 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 33L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_italian */
EIF_TYPED_VALUE F100_4058 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_japanese */
EIF_TYPED_VALUE F100_4059 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 17L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_korean */
EIF_TYPED_VALUE F100_4060 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_latvian */
EIF_TYPED_VALUE F100_4061 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 38L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_lithuanian */
EIF_TYPED_VALUE F100_4062 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 39L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_norwegian */
EIF_TYPED_VALUE F100_4063 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_polish */
EIF_TYPED_VALUE F100_4064 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 21L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_portuguese */
EIF_TYPED_VALUE F100_4065 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 22L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_romanian */
EIF_TYPED_VALUE F100_4066 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 24L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_russian */
EIF_TYPED_VALUE F100_4067 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 25L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_serbian */
EIF_TYPED_VALUE F100_4068 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 26L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_slovak */
EIF_TYPED_VALUE F100_4069 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 27L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_slovenian */
EIF_TYPED_VALUE F100_4070 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 36L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_spanish */
EIF_TYPED_VALUE F100_4071 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_swedish */
EIF_TYPED_VALUE F100_4072 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 29L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_thai */
EIF_TYPED_VALUE F100_4073 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 30L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_turkish */
EIF_TYPED_VALUE F100_4074 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 31L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_ukrainian */
EIF_TYPED_VALUE F100_4075 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 34L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.lang_vietnamese */
EIF_TYPED_VALUE F100_4076 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 42L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_saudi_arabia */
EIF_TYPED_VALUE F100_4077 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_german */
EIF_TYPED_VALUE F100_4078 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_iraq */
EIF_TYPED_VALUE F100_4079 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_german_swiss */
EIF_TYPED_VALUE F100_4080 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_egypt */
EIF_TYPED_VALUE F100_4081 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_german_austrian */
EIF_TYPED_VALUE F100_4082 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_libya */
EIF_TYPED_VALUE F100_4083 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_german_luxembourg */
EIF_TYPED_VALUE F100_4084 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_algeria */
EIF_TYPED_VALUE F100_4085 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_german_liechtenstein */
EIF_TYPED_VALUE F100_4086 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_morocco */
EIF_TYPED_VALUE F100_4087 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_italian */
EIF_TYPED_VALUE F100_4088 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_tunisia */
EIF_TYPED_VALUE F100_4089 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_italian_swiss */
EIF_TYPED_VALUE F100_4090 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_oman */
EIF_TYPED_VALUE F100_4091 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_korean */
EIF_TYPED_VALUE F100_4092 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_yemen */
EIF_TYPED_VALUE F100_4093 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_syria */
EIF_TYPED_VALUE F100_4094 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_neutral */
EIF_TYPED_VALUE F100_4095 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_jordan */
EIF_TYPED_VALUE F100_4096 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_norwegian_bokmal */
EIF_TYPED_VALUE F100_4097 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_lebanon */
EIF_TYPED_VALUE F100_4098 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_norwegian_nynorsk */
EIF_TYPED_VALUE F100_4099 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_kuwait */
EIF_TYPED_VALUE F100_4100 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_portuguese */
EIF_TYPED_VALUE F100_4101 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_uae */
EIF_TYPED_VALUE F100_4102 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_portuguese_brazilian */
EIF_TYPED_VALUE F100_4103 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_bahrain */
EIF_TYPED_VALUE F100_4104 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_serbian_latin */
EIF_TYPED_VALUE F100_4105 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_arabic_qatar */
EIF_TYPED_VALUE F100_4106 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_serbian_cyrillic */
EIF_TYPED_VALUE F100_4107 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_chinese_traditional */
EIF_TYPED_VALUE F100_4108 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish */
EIF_TYPED_VALUE F100_4109 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_chinese_simplified */
EIF_TYPED_VALUE F100_4110 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_mexican */
EIF_TYPED_VALUE F100_4111 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_chinese_hongkong */
EIF_TYPED_VALUE F100_4112 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_modern */
EIF_TYPED_VALUE F100_4113 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_chinese_singapore */
EIF_TYPED_VALUE F100_4114 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_guatemala */
EIF_TYPED_VALUE F100_4115 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_default */
EIF_TYPED_VALUE F100_4116 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_costa_rica */
EIF_TYPED_VALUE F100_4117 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_dutch */
EIF_TYPED_VALUE F100_4118 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_panama */
EIF_TYPED_VALUE F100_4119 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_dutch_belgian */
EIF_TYPED_VALUE F100_4120 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_dominican_republic */
EIF_TYPED_VALUE F100_4121 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_us */
EIF_TYPED_VALUE F100_4122 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_venezuela */
EIF_TYPED_VALUE F100_4123 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_uk */
EIF_TYPED_VALUE F100_4124 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_colombia */
EIF_TYPED_VALUE F100_4125 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_aus */
EIF_TYPED_VALUE F100_4126 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_peru */
EIF_TYPED_VALUE F100_4127 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_can */
EIF_TYPED_VALUE F100_4128 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_argentina */
EIF_TYPED_VALUE F100_4129 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_nz */
EIF_TYPED_VALUE F100_4130 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_ecuador */
EIF_TYPED_VALUE F100_4131 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_eire */
EIF_TYPED_VALUE F100_4132 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_chile */
EIF_TYPED_VALUE F100_4133 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_south_africa */
EIF_TYPED_VALUE F100_4134 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_uruguay */
EIF_TYPED_VALUE F100_4135 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_jamaica */
EIF_TYPED_VALUE F100_4136 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_paraguay */
EIF_TYPED_VALUE F100_4137 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_caribbean */
EIF_TYPED_VALUE F100_4138 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_bolivia */
EIF_TYPED_VALUE F100_4139 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_belize */
EIF_TYPED_VALUE F100_4140 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_el_salvador */
EIF_TYPED_VALUE F100_4141 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 17L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_english_trinidad */
EIF_TYPED_VALUE F100_4142 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_honduras */
EIF_TYPED_VALUE F100_4143 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_french */
EIF_TYPED_VALUE F100_4144 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_nicaragua */
EIF_TYPED_VALUE F100_4145 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 19L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_french_belgian */
EIF_TYPED_VALUE F100_4146 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_spanish_puerto_rico */
EIF_TYPED_VALUE F100_4147 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_french_canadian */
EIF_TYPED_VALUE F100_4148 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_swedish */
EIF_TYPED_VALUE F100_4149 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_french_swiss */
EIF_TYPED_VALUE F100_4150 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_swedish_finland */
EIF_TYPED_VALUE F100_4151 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_french_luxembourg */
EIF_TYPED_VALUE F100_4152 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_sys_default */
EIF_TYPED_VALUE F100_4153 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LANGUAGE_CONSTANTS}.sublang_korean_johab */
EIF_TYPED_VALUE F100_4154 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "sublang_korean_johab";
	RTEX;
	EIF_INTEGER_32 Result = ((EIF_INTEGER_32) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 99, Current, 0, 0, 4216);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(99, Current, 4216);
	RTIV(Current, RTAL);
	RTHOOK(1);
	RTDBGAL(0, 0x10000000, 1,0); /* Result */
	Result = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
}

void EIF_Minit100 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
